apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: merchant-service-lb
  labels:
    app: merchant
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app: merchant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: merchant-deployment
  labels:
    app: merchant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merchant
  template:
    metadata:
      labels:
        app: merchant
    spec:
      containers:
        - name: shop
          image: 10112018/merchant:latest
          resources: {}
          env:
            - name: "JAVA_OPTS"
              value: >-
                -Xms250m
                -Xmx450m
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: merchant-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: merchant-config
  namespace: app
data:
  config: |
    spring.application.name=merchant-service
    server.port=8081
    management.endpoints.web.exposure.include=*
    management.endpoint.health.show-details=ALWAYS
    management.security.enabled=false
    shopping-service-url-port=shop-service.app.svc.cluster.local
