apiVersion: v1
kind: Service
metadata:
  namespace: app
  name: shop-service
  labels:
    app: shop
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8082
  selector:
    app: shop
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: app
  name: shop-deployment
  labels:
    app: shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop
  template:
    metadata:
      labels:
        app: shop
    spec:
      containers:
        - name: shop
          image: 10112018/shop:latest
          env:
            - name: "JAVA_OPTS"
              value: >-
                -Xms250m
                -Xmx450m
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: shop-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-config
  namespace: app
data:
  config: |
    spring.application.name=shopping-service
    server.port=8082
    management.endpoints.web.exposure.include=*
    management.endpoint.health.show-details=ALWAYS
    management.security.enabled=false